name: CI Pipeline

on:
  push:
    branches:
      - '*'  # Trigger the workflow on any push to any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1  # Use v1 to avoid setup issues
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Explicitly specify the JDK distribution

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
          unzip gradle-7.4.2-bin.zip
          sudo mv gradle-7.4.2 /opt/gradle
          sudo ln -s /opt/gradle/bin/gradle /usr/local/bin/gradle
          gradle -v  # Verify Gradle installation

      - name: Build the application
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test

      - name: Check if build and tests passed
        run: |
          if [ $? -ne 0 ]; then
            echo "Build or tests failed. Exiting..."
            exit 1
          fi
