name: CI Pipeline

on:
  push:
    branches:
      - '*'  # This means the workflow will trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2  # Using v2 instead of v3
        with:
          java-version: '11'
          java-package: jdk  # Optional, defaults to 'jdk'
          check-latest: false

      - name: Build the application
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test
