name: CI Pipeline

on:
  push:
    branches:
      - '*'  # Trigger the workflow on any push to any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1  # Use v1, known to be stable and works
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Explicitly specify the JDK distribution

      - name: Build the application
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test
