name: CI Pipeline

on:
  push:
    branches:
      - '*'  # Trigger on all branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'
          check-latest: true
          cache: 'maven'

      - name: Build the application
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test
