name: CI Pipeline

on:
  push:
    branches:
      - '*'  # This will trigger the workflow on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure we are using the latest checkout action

      - name: Set up JDK 11
        uses: actions/setup-java@v2  # Use v2 instead of v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Use AdoptOpenJDK distribution explicitly
          cache: 'maven'  # Optional: use cache if you're working with Maven or Gradle

      - name: Build the application
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test
